{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Insurance API",
    "description" : "Insurance API Curd Operations",
    "version" : "2.0.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/DEEPIKA_2/InsuranceAgentAPI/2.0.0",
    "description" : "SwaggerHub API Auto Mocking"
  }, {
    "url" : "https://virtserver.swaggerhub.com/BHAGYASHRI_1/Insurance/1.0.0",
    "description" : "SwaggerHub API Auto Mocking"
  }, {
    "url" : "https://dev/Insurance/1.0.0",
    "description" : "Dev server"
  }, {
    "url" : "https://prod/Insurcance/1.0.0",
    "description" : "Production server"
  } ],
  "paths" : {
    "/agent" : {
      "get" : {
        "description" : "get agent list.",
        "parameters" : [ {
          "name" : "bodylimit",
          "in" : "query",
          "description" : "The amount of agents returned",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer"
          }
        }, {
          "name" : "pagelimit",
          "in" : "query",
          "description" : "The page to return insurance information",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Agent list retrieved successfully .",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/AgentList"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad request"
          },
          "401" : {
            "description" : "Unauthorized"
          }
        }
      },
      "post" : {
        "description" : "Submits a new agent,By passing in the appropriate options, you can Add new Agent in the system",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Agent"
              }
            },
            "application/xml" : {
              "schema" : {
                "$ref" : "#/components/schemas/Agent"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "The Agent submitted successfully."
          },
          "400" : {
            "description" : "Bad request"
          },
          "401" : {
            "description" : "Unauthorized"
          }
        }
      }
    },
    "/agent/{AgentID}" : {
      "get" : {
        "description" : "Retrieves a agent by ID",
        "parameters" : [ {
          "name" : "AgentID",
          "in" : "path",
          "description" : "The ID of the agent to retrieve",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string",
            "example" : "Agent000012334"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Agent retrieved successfully .",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/AgentList"
                }
              },
              "application/xml" : {
                "schema" : {
                  "$ref" : "#/components/schemas/AgentList"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad request"
          },
          "401" : {
            "description" : "Unauthorized"
          }
        }
      },
      "patch" : {
        "description" : "Update Agent",
        "parameters" : [ {
          "name" : "AgentID",
          "in" : "path",
          "description" : "The ID of the agent to retrieve",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "$ref" : "#/components/schemas/AgentPatch"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Agent updated successfully.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/AgentPatch"
                }
              },
              "application/xml" : {
                "schema" : {
                  "$ref" : "#/components/schemas/AgentPatch"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad request"
          },
          "401" : {
            "description" : "Unauthorized"
          }
        }
      }
    },
    "/quote" : {
      "get" : {
        "description" : "Retrieves a list of quotes.",
        "parameters" : [ {
          "name" : "bodylimit",
          "in" : "query",
          "description" : "The amount of quotes returned",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "maximum" : 20,
            "minimum" : 10,
            "type" : "integer",
            "example" : 15
          }
        }, {
          "name" : "pagelimit",
          "in" : "query",
          "description" : "The page to return insurance information",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "maximum" : 5,
            "minimum" : 1,
            "type" : "integer",
            "example" : 2
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "A list of quotes was successfully retrieved.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/QuotePost"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad request"
          },
          "401" : {
            "description" : "Unauthorized"
          }
        }
      },
      "post" : {
        "description" : "Submits a new quote.",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/QuotePost"
              }
            },
            "application/xml" : {
              "schema" : {
                "$ref" : "#/components/schemas/QuotePost"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "The quote was successfully submitted"
          },
          "400" : {
            "description" : "Bad request"
          },
          "401" : {
            "description" : "Unauthorized"
          }
        }
      }
    },
    "/quote/{quoteID}" : {
      "get" : {
        "description" : "Retrieves a quote by ID",
        "parameters" : [ {
          "name" : "quoteID",
          "in" : "path",
          "description" : "The ID of the quote to retrieve",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string",
            "example" : "SUB000012334"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "The quote was successfully retrieved.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/QuotePost"
                }
              },
              "application/xml" : {
                "schema" : {
                  "$ref" : "#/components/schemas/QuotePost"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad request"
          },
          "401" : {
            "description" : "Unauthorized"
          }
        }
      }
    },
    "/submission" : {
      "get" : {
        "description" : "Retrieves a list of quotes.",
        "parameters" : [ {
          "name" : "bodylimit",
          "in" : "query",
          "description" : "The amount of quotes returned",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "maximum" : 20,
            "minimum" : 10,
            "type" : "integer",
            "example" : 15
          }
        }, {
          "name" : "pagelimit",
          "in" : "query",
          "description" : "The page to return insurance information",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "maximum" : 5,
            "minimum" : 1,
            "type" : "integer",
            "example" : 2
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "A list of quotes was successfully retrieved.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Submission"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad request"
          },
          "401" : {
            "description" : "Unauthorized"
          }
        }
      },
      "post" : {
        "description" : "Submits a new submission.",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/SubmissionPost"
              }
            },
            "application/xml" : {
              "schema" : {
                "$ref" : "#/components/schemas/SubmissionPost"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "The quote was successfully submitted"
          },
          "400" : {
            "description" : "Bad request"
          },
          "401" : {
            "description" : "Unauthorized"
          }
        }
      }
    },
    "/policy" : {
      "get" : {
        "description" : "Retrieves a Policy by ID",
        "parameters" : [ {
          "name" : "PolicyID",
          "in" : "query",
          "description" : "The ID of the Policy to retrieve",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "example" : "Policy00001234"
          }
        }, {
          "name" : "FromDate",
          "in" : "query",
          "description" : "Enter From Date",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "toDate",
          "in" : "query",
          "description" : "Enter to Date",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "rowsPerPage",
          "in" : "query",
          "description" : "Enter Rows Per Page",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer"
          }
        }, {
          "name" : "preFetchPages",
          "in" : "query",
          "description" : "pre Fetch Pages",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Policy retrieved successfully .",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Policy"
                }
              },
              "application/xml" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Policy"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad request"
          },
          "401" : {
            "description" : "Unauthorized"
          }
        }
      },
      "post" : {
        "description" : "Submits a new policy,By passing in the appropriate options, you can Add new policy in the system",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Policy"
              }
            },
            "application/xml" : {
              "schema" : {
                "$ref" : "#/components/schemas/Policy"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "The Policy submitted successfully."
          },
          "400" : {
            "description" : "Bad request"
          },
          "401" : {
            "description" : "Unauthorized"
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Agents" : {
        "type" : "array",
        "description" : "Array of Agents info",
        "items" : {
          "$ref" : "#/components/schemas/Agents"
        }
      },
      "Agent" : {
        "properties" : {
          "FromDate" : {
            "type" : "string",
            "example" : "10/12/2022"
          },
          "toDate" : {
            "type" : "string",
            "example" : "12/12/2022"
          },
          "AgentID" : {
            "type" : "integer"
          },
          "AgentName" : {
            "type" : "string",
            "example" : "Hudson"
          },
          "logo" : {
            "type" : "object",
            "example" : "D:\\Azure Training\\project\\untitle.png"
          }
        },
        "description" : "Agent Inputs"
      },
      "AgentList" : {
        "properties" : {
          "FromDate" : {
            "type" : "string",
            "example" : "10/12/2022"
          },
          "toDate" : {
            "type" : "string",
            "example" : "12/12/2022"
          },
          "rowsPerPage" : {
            "type" : "integer",
            "example" : 10
          },
          "prefetchPages" : {
            "type" : "integer",
            "example" : 10
          },
          "AgentID" : {
            "type" : "integer"
          },
          "AgentName" : {
            "type" : "string",
            "example" : "Hudson"
          },
          "logo" : {
            "type" : "object",
            "example" : "D:\\Azure Training\\project\\untitle.png"
          }
        },
        "description" : "Agent Inputs"
      },
      "AgentPatch" : {
        "properties" : {
          "AgentID" : {
            "type" : "integer"
          },
          "logo" : {
            "type" : "object",
            "example" : "D:\\Azure Training\\project\\untitle.png"
          },
          "AgentName" : {
            "type" : "string",
            "example" : "Hudson"
          }
        },
        "description" : "Agent Inputs"
      },
      "Quotes" : {
        "type" : "array",
        "description" : "Array of quotes info",
        "items" : {
          "$ref" : "#/components/schemas/Quote"
        }
      },
      "Quote" : {
        "properties" : {
          "submissionNo" : {
            "type" : "string",
            "example" : "SUB00123434"
          },
          "applicantName" : {
            "type" : "string",
            "example" : "Liam"
          },
          "insuranceType" : {
            "type" : "string",
            "example" : "Home Health Care Insurance"
          }
        },
        "description" : "Model containing insurance info"
      },
      "QuotePost" : {
        "properties" : {
          "effectiveDate" : {
            "type" : "string",
            "example" : "08/29/22"
          },
          "retroDate" : {
            "type" : "string",
            "example" : "08/17/22"
          },
          "zipcode" : {
            "type" : "integer",
            "example" : 27612
          },
          "grossRevenues" : {
            "type" : "integer",
            "example" : 2500000
          },
          "noOfPhysicians" : {
            "type" : "integer",
            "example" : 1
          },
          "GL" : {
            "type" : "boolean",
            "example" : true
          },
          "EBL" : {
            "type" : "boolean",
            "example" : false
          },
          "HNOA" : {
            "type" : "boolean",
            "example" : false
          },
          "laser" : {
            "type" : "string",
            "example" : "full"
          },
          "retention" : {
            "type" : "integer",
            "example" : 0
          },
          "premium" : {
            "type" : "integer",
            "example" : 17023
          }
        },
        "description" : "Model containing Insurance info input"
      },
      "Submission" : {
        "properties" : {
          "fromDate" : {
            "type" : "string",
            "example" : "08/29/22"
          },
          "toDate" : {
            "type" : "string",
            "example" : "12/29/22"
          },
          "rowsPerPage" : {
            "type" : "integer",
            "example" : 5
          },
          "prefetchPages" : {
            "type" : "integer",
            "example" : 3
          }
        },
        "description" : "Model containing Submission info input"
      },
      "SubmissionPost" : {
        "properties" : {
          "fromDate" : {
            "type" : "string",
            "example" : "08/29/22"
          },
          "toDate" : {
            "type" : "string",
            "example" : "12/29/22"
          }
        },
        "description" : "Model containing Submission info input"
      },
      "Policy" : {
        "properties" : {
          "PolicyID" : {
            "type" : "integer"
          },
          "Premium" : {
            "type" : "integer",
            "example" : 50000
          },
          "Terms" : {
            "type" : "string",
            "example" : "Amount should not be less than 50000"
          },
          "Riders" : {
            "type" : "string",
            "example" : "add-on policy name"
          },
          "Effective From" : {
            "type" : "string",
            "example" : "15/12/2022"
          },
          "Active Till" : {
            "type" : "string",
            "example" : "15/12/2023"
          }
        },
        "description" : "Policy Inputs"
      }
    }
  }
}